### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by radarhere** [python-pillow/pillow-perf#119]
Would you mind renaming the master branch to main, as per https://github.com/python-pillow/Pillow/issues/5671?

It should be a simple matter of going to https://github.com/python-pillow/pillow-perf/settings/branches and renaming the default branch to main.

**Comment by homm** [comment]
Updated and made a fake commit to make the site alive https://python-pillow.org/pillow-perf/

**Comment by radarhere** [comment]
Thanks
