### ISSUE TITLE
Release "Pillow Performance" page

### ISSUE THREAD

**Issue by homm** [python-pillow/pillow-perf#38]
I'm happy to say that the [benchmarks page](https://python-pillow.org/pillow-perf/) is ready for release. There are lots of things which can be improved, most of them related to graphs. But the page itself is complete and can be useful for someone who are choosing library.

I'd like to ask @python-pillow/pillow-team to look at [the page](https://python-pillow.org/pillow-perf/). Does everything clear? Do you see any spelling errors?

When this issue will be addressed, I'm going to add short text to docs with a link to the page. Also I'd like to create posts on reddit and hacker news (many things were done since the last one).

**Comment by wiredfool** [comment]
There are definitely places where it needs some minor editing to make it sound more like a native speaker. I'll try to make a cut through it in the next day or two.

**Comment by aclark4life** [comment]
@homm Cool! I'll review, too

**Comment by homm** [comment]
Any updates? )

**Comment by aclark4life** [comment]
Opened #39

**Comment by homm** [comment]
Consider it as done )
