### ISSUE TITLE
AMD benchmark results

### ISSUE THREAD

**Issue by splav** [python-pillow/pillow-perf#40]
My configuration

Name: Own build desktop
OS: Arch Linux 64bit
CPU: AMD A10-7800 @ 3.50GHz, 
RAM: 32GB DDR3-2400

Important!
I had to change  opencv-python version to 3.1.0.**4** due to:
```
Collecting opencv-python==3.1.0.3
  Could not find a version that satisfies the requirement opencv-python==3.1.0.3 (from versions: 3.1.0.4, 3.1.0.5, 3.2.0.6)
No matching distribution found for opencv-python==3.1.0.3
```

Test output:
https://gist.githubusercontent.com/splav/174639f86a109dcc7d3eff12a0cf932e/raw/f552ce72af040204a245f2e3ad6586fb0eaf7245/pillow%2520perf%2520test

**Comment by homm** [comment]
Oh, thank you!
I'll update opencv version tooю

**Comment by homm** [comment]
By the way, which GCC versions is installed in your system?

**Comment by splav** [comment]
gcc 6.3.1
