### ISSUE TITLE
Add description and website to repo homepage

### ISSUE THREAD

**Issue by hugovk** [python-pillow/pillow-perf#43]
It'd be good to add a short description and https://python-pillow.org/pillow-perf/ in the "*No description, website, or topics provided*" bit at the top of the [repo frontpage](https://github.com/python-pillow/pillow-perf):

![image](https://cloud.githubusercontent.com/assets/1324225/22963074/7e4194e4-f359-11e6-8b2c-145c3db64c4b.png)

**Comment by homm** [comment]
Looks like I'm not an admin and can't do this.

@wiredfool @aclark4life, could you add description?

**Comment by aclark4life** [comment]
@homm @hugovk Done!

**Comment by hugovk** [comment]
Thanks!
