### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by radarhere** [python-pillow/pillow-perf#81]
I've found a few broken links.

https://github.com/python-pillow/pillow-perf/blob/master/docs/bundles/index.js#L10875 has a few broken links -
- https://github.com/python-pillow/pillow-perf/blob/master/docs/bundles/index.js#L10877 - https://dl.dropboxusercontent.com/u/34601363/toomuchscience.gif
- https://github.com/python-pillow/pillow-perf/blob/master/docs/bundles/index.js#L10898 - https://dl.dropboxusercontent.com/u/34601363/yeahscience.gif
- https://github.com/python-pillow/pillow-perf/blob/master/docs/bundles/index.js#L11623 - http://nnnick.github.io/Chart.js/docs-v2/#scales-time-scale

**Comment by homm** [comment]
This links in comments of a third-party component. Bundles is folder for compiled js and css files

**Comment by radarhere** [comment]
Fair enough. Thanks for replying
